### ISSUE TITLE
Loads new aerials quickly until it crashes or freezes

### ISSUE THREAD

**Issue by silvermoonstar3** [cachapa/AerialDream#4]
It worked for a week or two before it started doing this, I assume it's related to when there was an update to the app, but I didn't keep track of when it started (sorry!)
I've manually started it to show what's going on and it worked much better than usual (but still failed).  It goes to the daydream menu at the end because it only managed to crash itself this time instead of my entire TV.
I believe our TV is a Sony Bravia 4K Android TV, I could probably find more details if needed.
video:
https://goo.gl/photos/Hw3pAA2oQdFA9WDf6

**Comment by srygaard** [comment]
@cachapa I've not touched Android in years so take this with a grain of salt.  I saw this on reddit and got curious though.

One thought is that if onAttachedToWindow() was called multiple times, you could end up leaking a bunch of new VideoController() objects.  I didn't notice any check for this in AerialDream.java.

This could result in the application creating enough decoder contexts to make the codec throw an ExoPlaybackException, and in turn show that Error: null Toast.

Anyways, love the app!

**Comment by cachapa** [comment]
That could be it. It's strange that it would only happen on some devices, but it's worth checking.

I just saw on the reddit thread that the problem also happens on Mi Boxes. I don't have one either, but I'm at least more likely to get access to one than a Sony TV.

**Comment by silvermoonstar3** [comment]
I had an OS update a few days ago and it's at least a bit better!  Now, it functions normally for a minute or two before freezing on an image, which at least looks nicer and doesn't crash my entire TV.

**Comment by cachapa** [comment]
I just published an update which changes how videos are handled.
It's a long shot, but could you guys test it again?

**Comment by silvermoonstar3** [comment]
Unfortunately, the issue did not go away.  I checked that all software was up to date, did a full reset of the TV (long pressing power and all), tested, failed.  Found there was a button to cache first, tested that setting, also failed (I really thought that'd do it!)

**Comment by cachapa** [comment]
I just published a new version. I managed to find at least one major bug which was causing playback problems on an older tablet I have here.
It's one of those issues where I'm left wondering how it was working on other devices at all.

Anyway, would you mind testing again?

**Comment by silvermoonstar3** [comment]
Tried again (same as before minus trying the cache mode), still not working.

**Comment by cachapa** [comment]
Pity. Thanks again for testing. I'll continue looking

**Comment by silvermoonstar3** [comment]
Unrelated: it seems to have fixed a minor annoyance.  Previously, whenever leaving it, a small message "Error: Null" showed up at the bottom of the screen for a minute or so.  That's not happening anymore!

**Comment by srygaard** [comment]
I captured a logcat when the problem occurs on my Shield TV - [logcat.txt](https://github.com/cachapa/AerialDream/files/907829/logcat.txt)

onPlayerError() is looping on ExoPlaybackException which appears to be tied to bad media.  @cachapa if the media isn't advanced on exception it might just loop on the same bad stream.

**Comment by jeffwheeler** [comment]
@cachapa I experience this issue on my early-2015 Sony TV. The issue appears to be because the decoder is working on two streams simultaneously. I observed errors like [this one](https://github.com/google/ExoPlayer/issues/708) (my TV is using a MediaTek processor instead of QCOM).

**Comment by cachapa** [comment]
@jeffwheeler I was suspecting it was related to loading two videos simultaneously. After reading your link, it starts to make sense -- since video is decoded in HW, there might be cases where the decoder can only handle on stream at a time.

Aerial Dream needs two simultaneous streams in order to perform the fade transition at the end of each video. I don't really want to change that behaviour since it works so well in the current implementation, but maybe we could have an alternative for when the device only supports one stream.
That would involve rewriting large parts of the current code though so I'm not sure when I'll be able to work on it. Then there's still the issue of how to detect that situation.

**Comment by JackAGS** [comment]
Hi!
Any progress? I have the same problem :/
Other than that I love the app!

**Comment by JackAGS** [comment]
However, mine will manage to work normally for to videos and then it freezes on the next transition

**Comment by silvermoonstar3** [comment]
For what it's worth, mine has been playing nice for a while (months?) and
I've only been using it on the same TV that had issues before.  Only thing
that changed as far as I can tell is newer OS updates being released.

**Comment by sunrisela** [comment]
when I set the cache size, app will be crashed, this is logcat:

> 3134:02-01 17:01:50.808   752  1366 I ActivityManager: START u0 {cmp=com.codingbuffalo.aerialdream/.TestActivity} from uid 10068 on display 0
3135:02-01 17:01:50.810   801   816 D RSMouse : mFeatureEnabled=true  mPackageEnabled=false
3136:02-01 17:01:50.811 10004 10017 D MapperFramework: windowFocusChanged false com.codingbuffalo.aerialdream
3137:02-01 17:01:50.835 10004 10004 I ExoPlayerImpl: Init 1ec382 [ExoPlayerLib/2.8.4] [darcy, SHIELD, NVIDIA, 24]
3138:02-01 17:01:50.864 10004 10014 I art     : Background sticky concurrent mark sweep GC freed 12695(903KB) AllocSpace objects, 3(60KB) LOS objects, 34% free, 4MB/6MB, paused 9.546ms total 32.731ms
3139:02-01 17:01:50.864 10004 10004 I ExoPlayerImpl: Init 6bdbcef [ExoPlayerLib/2.8.4] [darcy, SHIELD, NVIDIA, 24]
3140:02-01 17:01:50.873 10004 10046 D NetworkSecurityConfig: No Network Security Config specified, using platform default
3141:02-01 17:01:50.875 10004 10004 D MapperFramework: ViewRootImpl ctr android.view.ViewRootImpl@27dbfdf  get base package name:com.codingbuffalo.aerialdream
3142:02-01 17:01:50.879   752  2552 D GameConsoleService: package=[com.codingbuffalo.aerialdream] class=[com.codingbuffalo.aerialdream.TestActivity] version=[1.0]
3143:02-01 17:01:50.879   752  2552 D GameConfigWindowManager: checkPackageName:  mPackageName=null mCurrPackageName=com.codingbuffalo.aerialdream
3144:02-01 17:01:50.879   752  2552 D GameConfigWindowManager: destoryGameConfigShowingWindow() in
3145:02-01 17:01:50.879   752  2552 D GameConsoleService: topActivityChanged, mTopPackageName: com.codingbuffalo.aerialdream
3146:02-01 17:01:50.879   752  2552 D GameConsoleService: Top class changed : com.codingbuffalo.aerialdream.SettingsActivity ----> com.codingbuffalo.aerialdream.TestActivity
3147:02-01 17:01:50.887   801  2672 D RSMouse : mFeatureEnabled=true  mPackageEnabled=false
3148:02-01 17:01:50.894   752  1365 D PowerManagerNotifier: onWakeLockAcquired: flags=536870922, tag="WindowManager", packageName=android, ownerUid=1000, ownerPid=752, workSource=WorkSource{10068}
3149:02-01 17:01:50.895 10004 10022 D MapperFramework: windowFocusChanged true com.codingbuffalo.aerialdream
3150:02-01 17:01:50.919  1408  1408 D ControllerMapper_S: App --> Mapper NewestApp com.codingbuffalo.aerialdream old :com.codingbuffalo.aerialdream
3151:02-01 17:01:50.919  1408  1408 D ControllerMapper_S: same binder for com.codingbuffalo.aerialdream skipping
3152:02-01 17:01:50.921   752   772 I ActivityManager: Displayed com.codingbuffalo.aerialdream/.TestActivity: +108ms
3153:02-01 17:01:51.346   752  1394 I WindowManager: Destroying surface Surface(name=com.codingbuffalo.aerialdream/com.codingbuffalo.aerialdream.SettingsActivity) called by com.android.server.wm.WindowStateAnimator.destroySurface:2018 com.android.server.wm.WindowStateAnimator.destroySurfaceLocked:882 com.android.server.wm.WindowState.destroyOrSaveSurface:2114 com.android.server.wm.WindowManagerService.tryStartExitingAnimation:3065 com.android.server.wm.WindowManagerService.relayoutWindow:2945 com.android.server.wm.Session.relayout:225 android.view.IWindowSession$Stub.onTransact:286 com.android.server.wm.Session.onTransact:146 
3154:02-01 17:01:51.508 10004 10004 D AndroidRuntime: Shutting down VM
3155:02-01 17:01:51.509 10004 10004 E GameConsoleCrashHandler: 10004******crash process name = com.codingbuffalo.aerialdream
3156:02-01 17:01:51.509 10004 10004 W System.err: java.lang.IllegalStateException: Another SimpleCache instance uses the folder: /data/user/0/com.codingbuffalo.aerialdream/cache
3157:02-01 17:01:51.509 10004 10004 W System.err: 	at com.google.android.exoplayer2.upstream.cache.SimpleCache.<init>(SimpleCache.java:124)
3158:02-01 17:01:51.509 10004 10004 W System.err: 	at com.google.android.exoplayer2.upstream.cache.SimpleCache.<init>(SimpleCache.java:111)
3159:02-01 17:01:51.509 10004 10004 W System.err: 	at com.google.android.exoplayer2.upstream.cache.SimpleCache.<init>(SimpleCache.java:83)
3160:02-01 17:01:51.509 10004 10004 W System.err: 	at com.codingbuffalo.aerialdream.ExoPlayerView.setUri(ExoPlayerView.java:79)
3161:02-01 17:01:51.509 10004 10004 W System.err: 	at com.codingbuffalo.aerialdream.VideoController.loadVideo(VideoController.java:118)
3162:02-01 17:01:51.509 10004 10004 W System.err: 	at com.codingbuffalo.aerialdream.VideoController.start(VideoController.java:72)
3163:02-01 17:01:51.509 10004 10004 W System.err: 	at com.codingbuffalo.aerialdream.VideoController$$Lambda$0.run(Unknown Source)
3164:02-01 17:01:51.509 10004 10004 W System.err: 	at android.os.Handler.handleCallback(Handler.java:751)
3165:02-01 17:01:51.509 10004 10004 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:95)
3166:02-01 17:01:51.509 10004 10004 W System.err: 	at android.os.Looper.loop(Looper.java:154)
3167:02-01 17:01:51.509 10004 10004 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6120)
3168:02-01 17:01:51.509 10004 10004 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
3169:02-01 17:01:51.509 10004 10004 W System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
3170:02-01 17:01:51.509 10004 10004 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
3171:02-01 17:01:51.510 10004 10004 I GameConsoleCrashHandler: createCrashDir in, crashDirPath=/storage/emulated/0/Android/data/com.codingbuffalo.aerialdream/files/gcs_bug_report
3172:02-01 17:01:51.511 10004 10004 I GameConsoleCrashHandler: createCrashDir: /storage/emulated/0/Android/data/com.codingbuffalo.aerialdream/files/gcs_bug_report already exists
3173:02-01 17:01:51.511 10004 10004 I GameConsoleCrashHandler: getErrorTimesToday >>> errorTimes=9
3174:02-01 17:01:51.512 10004 10004 D GameConsoleCrashHandler: Current crash times: 9
3175:02-01 17:01:51.512 10004 10004 I GameConsoleCrashHandler: createCrashDir in, crashDirPath=/storage/emulated/0/Android/data/com.codingbuffalo.aerialdream/files/gcs_bug_report
3176:02-01 17:01:51.512 10004 10004 I GameConsoleCrashHandler: createCrashDir: /storage/emulated/0/Android/data/com.codingbuffalo.aerialdream/files/gcs_bug_report already exists
3177:02-01 17:01:51.512 10004 10004 I GameConsoleCrashHandler: isCreateDirSucces = true
3178:02-01 17:01:51.512 10004 10004 I GameConsoleCrashHandler: save>>>errorTimes = 10
3179:02-01 17:01:51.512 10004 10004 D GameConsoleCrashHandler: isSaveSuccess = true
3180:02-01 17:01:51.512 10004 10004 D GameConsoleCrashHandler: constructCrashLog: in
3181:02-01 17:01:51.557 10004 10004 D GameConsoleCrashHandler: Save error times finish!
3182:02-01 17:01:51.558 10004 10004 D CrashReporterUtils: delCrashFilesIfOutOfLimit: dirPath:/storage/emulated/0/Android/data/com.codingbuffalo.aerialdream/files/gcs_bug_report

**Comment by cachapa** [comment]
I'm closing this issue and following this in #30
